#### Notes for later

In [1]:
import polars as pl
import plotly.express as px
import pandas as pd
import plotly.graph_objects as go
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter, date2num
import time

## Pull from file / make dates

In [2]:
last_month = time.localtime().tm_mon - 1

current_yr = time.localtime().tm_year

# handling if last month was January
if last_month == 0:
    last_month = 12
    current_yr = current_yr - 1


# current_month = 4
# current_yr = 2025

df = pl.read_csv(r"C:\Users\Denne\Documents\VSCodeProjects\FinancialStreamline2\BankStreamline\Data\CreditHistory.csv", 
                 truncate_ragged_lines=True,)


# date work ========================================== DELETE IF THE CODE BELOW WORKS ==================================================================
# df = df.with_columns(pl.col("Post Date")
#                         .str.split("/")
#                         .alias("split_str")
#                         .list.to_struct()) \
#                         .unnest('split_str') \
#                         .rename({'field_0':'month', 'field_1':'day', 'field_2':'year'}) \
#                         .cast({'day':pl.Int32, 'month':pl.Int32, 'year':pl.Int32}) \
#         .filter((pl.col('month') == last_month) & 
#                 (pl.col('year') == current_yr)) \
#         .with_columns(date = pl.concat_str([pl.col('year').cast(pl.Utf8), pl.lit('-'), pl.col('month').cast(pl.Utf8), pl.lit('-'), pl.col('day').cast(pl.Utf8)], separator="")) \
#         .with_columns(monthName = pl.col("date").str.strptime(pl.Date, "%Y-%m-%d").dt.strftime("%b")) \
#         .with_columns(weekDay = pl.col("date").str.strptime(pl.Date, "%Y-%m-%d").dt.strftime("%a")) \
#         .with_columns(quarter = pl.col("date").str.strptime(pl.Date, "%Y-%m-%d").dt.quarter())

df = df.with_columns(
                pl.col("Post Date").str.strptime(pl.Date, "%m/%d/%Y").alias("date")
                ).with_columns([
                pl.col("date").dt.month().alias("month"),
                pl.col("date").dt.day().alias("day"),
                pl.col("date").dt.year().alias("year")
                ]) \
        .filter((pl.col('month') == last_month) & 
                (pl.col('year') == current_yr)) \
        .with_columns(date = pl.concat_str([pl.col('year').cast(pl.Utf8), pl.lit('-'), pl.col('month').cast(pl.Utf8), pl.lit('-'), pl.col('day').cast(pl.Utf8)], separator="")) \
        .with_columns(monthName = pl.col("date").str.strptime(pl.Date, "%Y-%m-%d").dt.strftime("%b")) \
        .with_columns(weekDay = pl.col("date").str.strptime(pl.Date, "%Y-%m-%d").dt.strftime("%a")) \
        .with_columns(quarter = pl.col("date").str.strptime(pl.Date, "%Y-%m-%d").dt.quarter())


        
# The gate/clean up        
df = df.filter(pl.col('Amount') < 0) \
        .drop('Category', 'Reference Number') \
        .rename({'Amount':'cost', 'Description': 'description'}) \
        .with_columns(cardType = pl.lit('Credit')) \
        .with_columns(cost = abs(pl.col('cost')))


df.limit(10)

shape: (10, 11)
┌───────────┬───────────────────┬───────┬───────────┬───┬───────────┬─────────┬─────────┬──────────┐
│ Post Date ┆ description       ┆ cost  ┆ date      ┆ … ┆ monthName ┆ weekDay ┆ quarter ┆ cardType │
│ ---       ┆ ---               ┆ ---   ┆ ---       ┆   ┆ ---       ┆ ---     ┆ ---     ┆ ---      │
│ str       ┆ str               ┆ f64   ┆ str       ┆   ┆ str       ┆ str     ┆ i8      ┆ str      │
╞═══════════╪═══════════════════╪═══════╪═══════════╪═══╪═══════════╪═════════╪═════════╪══════════╡
│ 5/31/2026 ┆ WALMART.COM       ┆ 57.1  ┆ 2026-5-31 ┆ … ┆ May       ┆ Sun     ┆ 2       ┆ Credit   │
│           ┆ 800-9…            ┆       ┆           ┆   ┆           ┆         ┆         ┆          │
│ 5/31/2026 ┆ WALMART.COM       ┆ 65.91 ┆ 2026-5-31 ┆ … ┆ May       ┆ Sun     ┆ 2       ┆ Credit   │
│           ┆ 800-9…            ┆       ┆           ┆   ┆           ┆         ┆         ┆          │
│ 5/31/2026 ┆ WALMART.COM       ┆ 16.28 ┆ 2026-5-31 ┆ … ┆ May       ┆ Sun     ┆ 2       ┆ Credit   │
│           ┆ 800-9…            ┆       ┆           ┆   ┆           ┆         ┆         ┆          │
│ 5/29/2026 ┆ SHERWIN-WILLIAMS7 ┆ 67.98 ┆ 2026-5-29 ┆ … ┆ May       ┆ Fri     ┆ 2       ┆ Credit   │
│           ┆ 07335   EL DO…    ┆       ┆           ┆   ┆           ┆         ┆         ┆          │
│ 5/29/2026 ┆ SHERWIN-WILLIAMS7 ┆ 61.25 ┆ 2026-5-29 ┆ … ┆ May       ┆ Fri     ┆ 2       ┆ Credit   │
│           ┆ 07335   EL DO…    ┆       ┆           ┆   ┆           ┆         ┆         ┆          │
│ 5/29/2026 ┆ AMAZON            ┆ 8.22  ┆ 2026-5-29 ┆ … ┆ May       ┆ Fri     ┆ 2       ┆ Credit   │
│           ┆ PRIME*8Z8OK46E3   ┆       ┆           ┆   ┆           ┆         ┆         ┆          │
│           ┆ Amzn.…            ┆       ┆           ┆   ┆           ┆         ┆         ┆          │
│ 5/29/2026 ┆ WALMART.COM       ┆ 1.0   ┆ 2026-5-29 ┆ … ┆ May       ┆ Fri     ┆ 2       ┆ Credit   │
│           ┆ 8009256278        ┆       ┆           ┆   ┆           ┆         ┆         ┆          │
│           ┆ BENTO…            ┆       ┆           ┆   ┆           ┆         ┆         ┆          │
│ 5/29/2026 ┆ WALMART.COM       ┆ 7.25  ┆ 2026-5-29 ┆ … ┆ May       ┆ Fri     ┆ 2       ┆ Credit   │
│           ┆ 8009256278        ┆       ┆           ┆   ┆           ┆         ┆         ┆          │
│           ┆ 800-9…            ┆       ┆           ┆   ┆           ┆         ┆         ┆          │
│ 5/29/2026 ┆ MURPHY 1111       ┆ 3.29  ┆ 2026-5-29 ┆ … ┆ May       ┆ Fri     ┆ 2       ┆ Credit   │
│           ┆ EL DO…            ┆       ┆           ┆   ┆           ┆         ┆         ┆          │
│ 5/28/2026 ┆ WALMART.COM       ┆ 6.56  ┆ 2026-5-28 ┆ … ┆ May       ┆ Thu     ┆ 2       ┆ Credit   │
│           ┆ 800-9…            ┆       ┆           ┆   ┆           ┆         ┆         ┆          │
└───────────┴───────────────────┴───────┴───────────┴───┴───────────┴─────────┴─────────┴──────────┘

# Categorize

In [3]:
# pulls from the categorize py file

from Categorize import make_categories
import Categorize
import importlib
importlib.reload(Categorize)


df = make_categories(df)

df.limit(3)

shape: (3, 11)
┌───────────┬──────────┬─────────────────────────┬───────┬───┬──────┬─────────┬──────────┬─────────┐
│ date      ┆ category ┆ description             ┆ cost  ┆ … ┆ year ┆ weekDay ┆ cardType ┆ quarter │
│ ---       ┆ ---      ┆ ---                     ┆ ---   ┆   ┆ ---  ┆ ---     ┆ ---      ┆ ---     │
│ str       ┆ str      ┆ str                     ┆ f64   ┆   ┆ i32  ┆ str     ┆ str      ┆ i8      │
╞═══════════╪══════════╪═════════════════════════╪═══════╪═══╪══════╪═════════╪══════════╪═════════╡
│ 2026-5-31 ┆ wmt      ┆ WALMART.COM             ┆ 57.1  ┆ … ┆ 2026 ┆ Sun     ┆ Credit   ┆ 2       │
│           ┆          ┆ 800-9…                  ┆       ┆   ┆      ┆         ┆          ┆         │
│ 2026-5-31 ┆ wmt      ┆ WALMART.COM             ┆ 65.91 ┆ … ┆ 2026 ┆ Sun     ┆ Credit   ┆ 2       │
│           ┆          ┆ 800-9…                  ┆       ┆   ┆      ┆         ┆          ┆         │
│ 2026-5-31 ┆ wmt      ┆ WALMART.COM             ┆ 16.28 ┆ … ┆ 2026 ┆ Sun     ┆ Credit   ┆ 2       │
│           ┆          ┆ 800-9…                  ┆       ┆   ┆      ┆         ┆          ┆         │
└───────────┴──────────┴─────────────────────────┴───────┴───┴──────┴─────────┴──────────┴─────────┘

### Look at last month's misc

In [4]:
list(df.filter(pl.col('category') == 'misc')['description'].unique())
# df.filter(pl.col('category') == 'misc')

['MINIMUM INTEREST CHARGE',
 'FOREIGN TRANSACTION FEE - MERCHANDISE',
 'SQ *ARKANSAS WEATHER WATCLittle Rock  AR']

#### Make sure correct month/year is being loaded

In [6]:
print(list(df['month'].unique()))
print(list(df['monthName'].unique()))
print(list(df['weekDay'].unique()))
print(list(df['year'].unique()))
print(df.select(pl.col("date").min()))
print(df.select(pl.col("date").max())) # broken, looks at str, not date

[5]
['May']
['Mon', 'Thu', 'Sat', 'Sun', 'Tue', 'Fri', 'Wed']
[2026]
shape: (1, 1)
┌──────────┐
│ date     │
│ ---      │
│ str      │
╞══════════╡
│ 2026-5-1 │
└──────────┘
shape: (1, 1)
┌──────────┐
│ date     │
│ ---      │
│ str      │
╞══════════╡
│ 2026-5-8 │
└──────────┘

### Check number of rows (30ish per month)
Apr: 32
<br>May: 21
<br>June: 20
<br>July: 23
<br>Aug: 28
<br>Sep: 35
<br>Oct: 44
<br>Nov: 15
<br>Dec: 44
<br>2026 - Credit card raises limit
<br>Jan: 57
<br>Feb: 55
<br>Mar: 83
<br>Apr: 86
<br>May: 84

In [8]:
len(df)

84

### Load the data (handle w/ caution)

In [ ]:
# path = r'C:\Users\Denne\Documents\VSCodeProjects\FinancialStreamline2\BankStreamline\Data\BankDataProd.csv'


# with open(path, mode="a", encoding="utf-8") as f:
#    df.write_csv(f, include_header=False)